# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"
  bash_completion "completions/craft-cli.bash"
  zsh_completion "completions/_craft-cli"
  fish_completion "completions/craft-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "0e9b4be07c85ff0afc82385b5eb4351c56b68d6966580688fb292a25ed11b18c"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "165ac5438627195b71ad5a35e905a85da71f7c62ffb604b4128ba2ea7db0db92"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "61e08f92a7daeee46b579ab08d5cf51946b7bd42860b366200f2d47a6f027657"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "97e8fedeedd52d6f405ca7e9f30a9e28d87d4ca24cca5c86562bdd594047d85a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/craft-cli"]
    end
    system_command "#{staged_path}/craft-cli", args: ["version"], print_stdout: true
  end

  # No zap stanza required
end
