# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"
  bash_completion "completions/craft-cli.bash"
  zsh_completion "completions/_craft-cli"
  fish_completion "completions/craft-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "4fd5d70eee6ba85256a7bf0c4e1bef055892c87a4c06ff7cdd29d940c82cc419"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "65cd741437ee878dfcf332451c8fbdcb4af0afe55093b6b8370ff214109cb925"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "084cda38bed1e0fb50e7fe555726e7a2099876f0fb98362ca5e977adfb2243e6"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "91a1816d8db6c0104d8464c694e864d7ac2191846c1cdd8751815438821c1ad5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/craft-cli"]
    end
    system_command "#{staged_path}/craft-cli", args: ["version"], print_stdout: true
  end

  # No zap stanza required
end
