# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"
  bash_completion "completions/craft-cli.bash"
  zsh_completion "completions/_craft-cli"
  fish_completion "completions/craft-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "e12df1325f5ca525b4c910d6979e3657d6175dd86c1afda11e1c3d07b9e256b0"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "7c54e8133297ddadb0a1fa013f54830804f0f84000986ac29e04f46b93962a74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "ac22a3565f4b01a5c4189cacc0acff03d14fa9b2fab8726d71b9b834f787b7bd"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "77d78d1b8dc9d1cd07364623d38f1e8c94963eee6ccb05dbefee7c5743775123"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/craft-cli"]
    end
    system_command "#{staged_path}/craft-cli", args: ["version"], print_stdout: true
  end

  # No zap stanza required
end
